<?php
$params=sf_range_params($analytics);$range=$analytics['range']??[];$total=(int)($summary['total']??0);$previous=(int)($summary['previous_total']??0);$delta=$previous>0?($total-$previous)/$previous*100:null;$trend=$analytics['trend']??[];
?>
<div class="page-heading"><div><div class="eyebrow">看见分享的走向</div><h1>数据分析</h1><p>所有图表与下载记录使用同一口径，可直接下钻核对。</p></div><?php sf_range_control('/admin/analytics',$analytics) ?></div>
<div class="analytics-range-note"><?= sf_icon('calendar') ?><span><?= h($range['start']??'') ?> 至 <?= h($range['end']??'') ?></span><span><?= h($timezone) ?></span><?php if(count(array_intersect_key($params,array_flip(['file_id','region','referrer','ip','status'])))): ?><a href="<?= h(sf_url('/admin/analytics',['days'=>$range['days']??30])) ?>">清除附加筛选</a><?php endif ?></div>
<div class="metrics-grid analytics-metrics">
<a class="metric-card" href="<?= h(sf_url('/admin/downloads',$params)) ?>"><div class="metric-label">公开下载会话<span class="metric-icon"><?= sf_icon('download') ?></span></div><div class="metric-value"><?= sf_number($total) ?><span>次</span></div><div class="metric-bottom"><span class="<?= $delta!==null&&$delta>0?'positive-text':'' ?>"><?php if($delta===null): ?>前期无记录，不计算增长率<?php else: ?>较前 <?= (int)($range['days']??30) ?> 天 <?= $delta>0?'+':'' ?><?= number_format($delta,1) ?>%<?php endif ?></span><?= sf_icon('arrow') ?></div></a>
<a class="metric-card" href="<?= h(sf_url('/admin/downloads',$params)) ?>"><div class="metric-label">独立 IP<span class="metric-icon purple"><?= sf_icon('globe') ?></span></div><div class="metric-value"><?= sf_number($summary['unique_ips']??0) ?><span>个</span></div><div class="metric-bottom"><span>按 IP 去重，不等同于独立访客</span><?= sf_icon('arrow') ?></div></a>
<a class="metric-card" href="<?= h(sf_url('/admin/downloads',$params)) ?>"><div class="metric-label">已观察发送量<span class="metric-icon teal"><?= sf_icon('server') ?></span></div><div class="metric-value bytes-metric"><?= h(format_bytes((int)($summary['observed_bytes']??0))) ?></div><div class="metric-bottom"><span>服务器观察，含重试与续传</span><?= sf_icon('arrow') ?></div></a>
</div>
<section class="panel trend-panel analytics-trend"><div class="panel-heading"><div><h2>公开下载趋势</h2><p>按当前时区逐日汇总，缺失日期以 0 补齐</p></div><span class="chart-legend"><i></i>公开下载</span></div><?php sf_line_chart($trend,$params,'analytics-trend') ?></section>
<div class="analytics-grid"><section class="panel"><div class="panel-heading"><div><h2>近似地区</h2><p>按网络出口归属地统计</p></div><?= sf_icon('globe') ?></div><?php sf_rank_list($analytics['regions']??[],'regions',$params,10) ?><div class="panel-footnote">未知地区同样计入总数。VPN、移动网络可能影响归属地，低样本不代表稳定趋势。</div></section><section class="panel"><div class="panel-heading"><div><h2>一天中的下载时段</h2><p><?= h($timezone) ?> · 0–23 点实际次数</p></div><?= sf_icon('clock') ?></div><?php sf_hours_chart($analytics['hours']??[]) ?><div class="panel-footnote">汇总所选日期内每个小时的次数；夏令时回拨产生的重复时段合并计入同一小时。</div></section></div>
<div class="analytics-grid"><section class="panel"><div class="panel-heading"><div><h2>热门文件</h2><p>包含暂停、回收与销毁文件的历史</p></div><?= sf_icon('folder') ?></div><?php sf_rank_list($analytics['files']??[],'files',$params,8) ?></section><section class="panel"><div class="panel-heading"><div><h2>下载来源</h2><p>仅展示经过清洗的域名与路径</p></div><?= sf_icon('link') ?></div><?php sf_rank_list($analytics['referrers']??[],'referrers',$params,8) ?><div class="panel-footnote">没有 Referer 时显示“直接访问 / 未提供来源”。来源可能缺失或被修改，不作为身份依据。</div></section></div>
<section class="methodology-note"><span><?= sf_icon('info') ?></span><div><h3>理解这些数字</h3><p>分析仅统计升级后有明细的公开下载会话，已排除管理下载、密码验证、HEAD 与拒绝请求。全站历史迁入累计 <?= sf_number($summary['legacy_total']??0) ?> 次，仅用于总累计，不被编造成趋势、地区或来源记录。</p><a class="text-link" href="<?= h(sf_url('/admin/downloads',$params)) ?>">查看同条件明细<?= sf_icon('arrow') ?></a></div></section>
