<?php
$filters=$data['filters']??$_GET;$analytics['range']=$data['range']??($analytics['range']??[]);$rangeParams=sf_range_params($analytics);$isAttempts=($data['log_tab']??'')==='attempts';$event=$data['event']??null;
?>
<div class="page-heading"><div><div class="eyebrow">每次访问，都有上下文</div><h1>下载记录</h1><p>查看公开下载会话，以及服务器观察到的传输情况。</p></div><?php if(!$isAttempts): ?><a class="button secondary" href="<?= h(sf_query_url('/admin/downloads/export',['id'=>null,'page'=>null,'tab'=>null])) ?>"><?= sf_icon('download') ?>导出 CSV</a><?php endif ?></div>
<div class="view-tabs"><a class="<?= !$isAttempts?'active':'' ?>" href="<?= h(sf_query_url('/admin/downloads',['tab'=>null,'id'=>null,'page'=>null])) ?>" <?= !$isAttempts?'aria-current="page"':'' ?>>公开下载会话</a><a class="<?= $isAttempts?'active':'' ?>" href="<?= h(sf_query_url('/admin/downloads',['tab'=>'attempts','id'=>null,'page'=>null])) ?>" <?= $isAttempts?'aria-current="page"':'' ?>>访问尝试</a></div>
<?php if($event&&!$isAttempts): ?>
<section class="panel event-detail"><div class="panel-heading"><div><span class="eyebrow">公开下载会话 #<?= (int)$event['id'] ?></span><h2><?= h($event['filename']) ?></h2></div><a class="icon-button" href="<?= h(sf_query_url('/admin/downloads',['id'=>null])) ?>" aria-label="关闭会话详情"><?= sf_icon('close') ?></a></div><div class="event-detail-body"><div class="event-status-row"><?= sf_transfer_badge($event['status']) ?><a class="text-link" href="/admin/files/<?= (int)$event['file_id'] ?>">文件详情<?= sf_icon('arrow') ?></a></div><dl class="event-properties"><div><dt>获准开始</dt><dd><?= h(sf_date($event['started_at'],$timezone)) ?><small><?= h((new DateTimeImmutable('@'.$event['started_at']))->setTimezone(new DateTimeZone($timezone))->format('c')) ?></small></dd></div><div><dt>最近请求</dt><dd><?= h(sf_date($event['last_request_at'],$timezone)) ?></dd></div><div><dt>客户端 IP</dt><dd class="mono"><?= h($event['ip']) ?><small><?= h(match($event['ip_source']){'trusted_proxy','trusted-proxy'=>'来自核实的可信代理链','peer'=>'来自实际连接对端',default=>$event['ip_source']}) ?></small></dd></div><div><dt>近似地区</dt><dd><?= h($event['region']?:'未知') ?><small>地区库：<?= h($event['geo_version']?:'未配置') ?></small></dd></div><div><dt>来源</dt><dd class="break-word"><?= h($event['referrer']?:'直接访问 / 未提供来源') ?><small>来源经过清洗，可能缺失或被客户端修改</small></dd></div><div><dt>文件快照</dt><dd>文件 #<?= (int)$event['file_id'] ?> · v<?= (int)$event['version'] ?><small><?= h($event['filename']) ?></small></dd></div><div><dt>传输请求</dt><dd><?= sf_number($event['request_count']) ?> 次<small>同一会话的续传不重复计数</small></dd></div><div><dt>已观察发送量</dt><dd><?= h(format_bytes((int)$event['observed_bytes'])) ?><small>HTTP <?= h($event['http_status']??'未知') ?> · 不代表客户端已保存</small></dd></div></dl><details class="diagnostic-details"><summary><?= sf_icon('code') ?>HTTP / Range 传输诊断 <span><?= sf_number(count($data['transfers']??[])) ?> 次请求</span><?= sf_icon('chevron-down') ?></summary><div class="table-wrap"><table class="data-table diagnostic-table"><thead><tr><th>请求时间</th><th>HTTP</th><th>Range</th><th>服务器观察</th><th>结果</th></tr></thead><tbody><?php foreach(($data['transfers']??[])as$transfer): ?><tr><td data-label="请求时间" class="mono"><?= h(sf_date($transfer['started_at'],$timezone)) ?></td><td data-label="HTTP"><?= (int)$transfer['http_status'] ?></td><td data-label="Range" class="mono break-word"><?= h($transfer['range_header']?:'完整文件') ?></td><td data-label="已发送 / 预期"><?= h(format_bytes((int)$transfer['observed_bytes'])) ?> / <?= h(format_bytes((int)$transfer['expected_bytes'])) ?></td><td data-label="结果"><?= sf_transfer_badge($transfer['status']) ?></td></tr><?php endforeach ?></tbody></table></div></details></div></section>
<?php endif ?>
<?php if($isAttempts): ?>
<div class="notice info"><?= sf_icon('info') ?><span>最近 100 次访问尝试，仅用于排查未获准的请求，不计入公开下载数。此列表不应用下载会话的日期与地区筛选。</span></div>
<section class="panel"><div class="panel-heading"><div><h2>未获准的访问</h2><p>密码验证失败、暂停、额度不足与其他拒绝结果</p></div><span class="small-badge">不计数</span></div><?php if(empty($data['attempts'])): sf_empty('shield','没有需要查看的访问尝试','未获准请求出现后，会在这里留下不包含密码或授权 token 的记录。'); else: ?><div class="table-wrap"><table class="data-table attempts-table"><thead><tr><th>文件</th><th>请求时间</th><th>客户端 IP</th><th>结果</th><th>HTTP</th></tr></thead><tbody><?php foreach($data['attempts']as$attempt): ?><tr><td data-label="文件"><?php if(!empty($attempt['file_id'])): ?><a class="file-name" href="/admin/files/<?= (int)$attempt['file_id'] ?>"><?= h($attempt['filename']??'文件 #'.$attempt['file_id']) ?></a><?php else: ?>无法识别的文件<?php endif ?></td><td data-label="请求时间" class="mono"><?= h(sf_date($attempt['occurred_at'],$timezone)) ?></td><td data-label="客户端 IP" class="mono"><?= h($attempt['ip']) ?></td><td data-label="结果"><?= h(match($attempt['reason']){'password'=>'密码验证失败','rate_limit'=>'请求过于频繁','not_found'=>'文件不存在','expired'=>'授权已过期',default=>sf_status_label($attempt['reason'])==='状态未知'?$attempt['reason']:sf_status_label($attempt['reason'])}) ?></td><td data-label="HTTP"><?= (int)$attempt['http_status'] ?></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></section>
<?php else: ?>
<section class="panel logs-panel"><div class="logs-controls"><div class="filter-heading"><strong>筛选记录</strong><span><?= h($analytics['range']['start']??'') ?> 至 <?= h($analytics['range']['end']??'') ?></span></div><?php sf_range_control('/admin/downloads',$analytics) ?></div>
<form method="get" action="/admin/downloads" class="log-filters" aria-label="筛选下载会话">
<?php foreach(['days','start','end']as$key)if(isset($rangeParams[$key])): ?><input type="hidden" name="<?= h($key) ?>" value="<?= h($rangeParams[$key]) ?>"><?php endif ?>
<label>文件<select name="file_id"><option value="">全部文件（含历史）</option><?php foreach($files as$f): ?><option value="<?= (int)$f['id'] ?>" <?= (string)($filters['file_id']??'')===(string)$f['id']?'selected':'' ?>><?= h($f['name']) ?></option><?php endforeach ?></select></label>
<label>传输状态<select name="status"><option value="">全部状态</option><?php foreach(['server_finished','interrupted','unknown']as$status): ?><option value="<?= h($status) ?>" <?= ($filters['status']??'')===$status?'selected':'' ?>><?= h(sf_transfer_label($status)) ?></option><?php endforeach ?></select></label>
<label>近似地区<input name="region" value="<?= h($filters['region']??'') ?>" placeholder="全部地区"></label>
<details class="advanced-filters" <?= !empty($filters['ip'])||!empty($filters['referrer'])?'open':'' ?>><summary class="button ghost"><?= sf_icon('filter') ?>更多筛选<?= sf_icon('chevron-down') ?></summary><div><label>完整 IP<input name="ip" value="<?= h($filters['ip']??'') ?>" placeholder="IPv4 / IPv6" autocomplete="off"></label><label>来源<input name="referrer" value="<?= h($filters['referrer']??'') ?>" placeholder="域名与安全路径"><small>未提供来源可填 __direct__</small></label></div></details>
<button class="button primary" type="submit">应用筛选</button><a class="button ghost" href="/admin/downloads">重置</a>
</form>
<div class="record-count"><strong><?= sf_number($pagination['total']??0) ?></strong> 次公开下载会话<span>管理下载已排除</span></div>
<?php sf_events_table($events,$timezone) ?><?php sf_pagination($pagination,'/admin/downloads') ?>
</section>
<div class="definition-note"><?= sf_icon('info') ?><p>地区是网络出口的近似位置。来源可能被裁剪或伪造；“直接访问 / 未提供来源”并不能证明访问来源。公开下载按首次获准开始计数。</p></div>
<?php endif ?>
