<?php
$tab=in_array($_GET['tab']??'overview',['overview','sharing','downloads'],true)?($_GET['tab']??'overview'):'overview';$fileId=(int)$file['id'];$fileUrl='/admin/files/'.$fileId;$publicUrl=public_download_url($file);$unavailable=in_array($file['state'],['destroying','destroyed','missing','trashed'],true);$policyLocked=in_array($file['state'],['destroying','destroyed','trashed'],true);[$typeIcon,$typeColor,$typeLabel]=sf_file_type($file);
?>
<div class="back-navigation"><a class="text-link" href="/admin/files"><?= sf_icon('back') ?>所有文件</a></div>
<div id="detail-page-content" data-file-detail="<?= $fileId ?>">
<div class="file-detail-heading"><div class="file-detail-identity"><?= sf_file_icon($file,'large') ?><div><span class="eyebrow">文件详情 · v<?= (int)$file['version'] ?></span><h1><?= h($file['name']) ?></h1><div class="file-detail-meta"><span><?= h(format_bytes($file['bytes'])) ?></span><span><?= h($typeLabel) ?></span><?= sf_badge($file['state']) ?></div></div></div><div class="heading-actions"><button class="button primary" type="button" data-copy="<?= h($publicUrl) ?>" data-copy-label="分享链接"><?= sf_icon('copy') ?>复制链接</button><?php if(!$unavailable): ?><form method="post" action="<?= h($fileUrl) ?>/download-ticket" class="inline-form" data-download-form><?php sf_csrf($manager) ?><button class="button secondary" type="submit" title="不使用公开名额，不计入公开统计"><?= sf_icon('download') ?>后台下载</button></form><?php endif ?></div></div>
<div class="detail-tabs" aria-label="文件详情页签"><a href="<?= h($fileUrl) ?>?tab=overview" class="<?= $tab==='overview'?'active':'' ?>" <?= $tab==='overview'?'aria-current="page"':'' ?>>概况</a><a href="<?= h($fileUrl) ?>?tab=sharing" class="<?= $tab==='sharing'?'active':'' ?>" <?= $tab==='sharing'?'aria-current="page"':'' ?>>分享设置</a><a href="<?= h($fileUrl) ?>?tab=downloads" class="<?= $tab==='downloads'?'active':'' ?>" <?= $tab==='downloads'?'aria-current="page"':'' ?>>下载记录</a></div>
<?php if($file['state']!=='active'): ?>
<div class="notice <?= in_array($file['state'],['missing','destroying'],true)?'warning':'info' ?>"><?= sf_icon(in_array($file['state'],['missing','destroying'],true)?'alert':'info') ?><span><?= h(match($file['state']){'paused'=>'分享已暂停，新的公开下载不会开始；已经获准的会话仍可继续。','exhausted'=>'下载名额已用完。增加名额或改为不限次后，可以重新开放分享。','missing'=>'服务器上的文件实体缺失或已变更。请检查目录并重新扫描，历史记录不会丢失。','destroy_pending'=>'已到达下载额度，正在等待有效会话结束。追加名额或关闭自动销毁可取消等待。','destroying'=>'正在永久删除服务器文件，此阶段无法取消或开始新的下载。','destroyed'=>'服务器文件已永久销毁，无法从本应用恢复。元数据与公开下载历史仍然保留。','trashed'=>'文件已移入回收目录。可以恢复为暂停状态，再检查分享设置。',default=>'当前分享不可用。'}) ?></span></div>
<?php endif ?>
<?php if($tab==='overview'): ?>
<div class="detail-metrics"><div><span>公开累计</span><strong><?= sf_number($file['public_count']) ?><small> 次</small></strong></div><div><span>剩余名额</span><strong><?= $file['remaining']===null?'不限次':sf_number($file['remaining']) ?><small><?= $file['remaining']===null?'':' 次' ?></small></strong></div><div><span>历史迁入累计</span><strong><?= sf_number($file['legacy_count']) ?><small> 次</small></strong></div><div><span>升级后明细</span><strong><?= sf_number(max(0,$file['public_count']-$file['legacy_count'])) ?><small> 次</small></strong></div></div>
<div class="detail-columns"><section class="panel"><div class="panel-heading"><h2>文件信息</h2><span class="subtle-label">稳定 ID #<?= $fileId ?></span></div><dl class="property-list"><div><dt>文件名称</dt><dd><?= h($file['name']) ?></dd></div><div><dt>文件类型</dt><dd class="mono"><?= h($file['mime_type']) ?></dd></div><div><dt>文件大小</dt><dd><?= h(format_bytes($file['bytes'])) ?> <small>（<?= sf_number($file['bytes']) ?> 字节）</small></dd></div><div><dt>当前版本</dt><dd>v<?= (int)$file['version'] ?></dd></div><div><dt>导入时间</dt><dd class="mono"><?= h(sf_date($file['created_at'],$timezone)) ?></dd></div><div><dt>最近公开下载</dt><dd class="mono"><?= h(sf_date($file['last_public_at'],$timezone)) ?></dd></div><div><dt>SHA256</dt><dd><?php if($file['sha256']): ?><div class="hash-value"><code title="<?= h($file['sha256']) ?>"><?= h(substr($file['sha256'],0,12).'…'.substr($file['sha256'],-12)) ?></code><button class="icon-button" type="button" data-copy="<?= h($file['sha256']) ?>" data-copy-label="完整 SHA256" aria-label="复制完整 SHA256"><?= sf_icon('copy') ?></button></div><details class="hash-details"><summary>查看完整校验值</summary><code><?= h($file['sha256']) ?></code></details><?php else: ?><span class="muted">实体不可用，暂无校验值</span><?php endif ?></dd></div></dl></section>
<section class="panel link-panel"><div class="panel-heading"><h2>分享链接</h2><?= sf_icon('link') ?></div><div class="link-box"><span class="muted">稳定公开入口</span><p><?= h($publicUrl) ?></p><button class="button secondary full-width" type="button" data-copy="<?= h($publicUrl) ?>" data-copy-label="分享链接"><?= sf_icon('copy') ?>复制链接</button></div><div class="share-properties"><div><?= sf_icon($file['has_password']?'lock':'unlock') ?><span><?= $file['has_password']?'需要分享密码':'无需密码，直接下载' ?></span></div><div><?= sf_icon('clock') ?><span><?= $file['remaining']===null?'下载次数不限':'还可开始 '.sf_number($file['remaining']).' 次下载' ?></span></div><div><?= sf_icon('shield') ?><span><?= $file['auto_destroy']?'到额后自动永久销毁':'到额仅停止新下载' ?></span></div></div><a class="text-link" href="<?= h($publicUrl) ?>" target="_blank" rel="noopener noreferrer">查看公开入口<?= sf_icon('external') ?></a><p class="form-hint">打开公开入口将遵循密码与配额规则，并计入公开下载。管理员取文件请用“后台下载”。</p></section></div>
<section class="panel"><div class="panel-heading"><h2>最近下载</h2><a class="text-link" href="<?= h($fileUrl) ?>?tab=downloads">全部记录<?= sf_icon('arrow') ?></a></div><?php sf_events_table(array_slice($events,0,5),$timezone,true) ?></section>
<?php elseif($tab==='sharing'): ?>
<section class="panel visibility-panel"><div><h2>公开首页展示</h2><p>只有开启此项且文件可下载时，访客才会在首页看到它。隐藏不会使已发出的分享链接失效；需要停止下载请暂停分享。</p></div><form method="post" action="<?= h($fileUrl) ?>/visibility"><?php sf_csrf($manager) ?><input type="hidden" name="view" value="detail"><input type="hidden" name="visible" value="<?= $file['homepage_visible']?'0':'1' ?>"><button type="submit" role="switch" aria-checked="<?= $file['homepage_visible']?'true':'false' ?>" aria-label="在首页显示" class="visibility-switch"><span class="switch-track" aria-hidden="true"></span><span>在首页显示</span><strong><?= $file['homepage_visible']?'开':'关' ?></strong></button></form></section>
<?php if($policyLocked): ?><section class="panel"><?php sf_empty('archive','当前无法更改分享设置',$file['state']==='trashed'?'请先在下方恢复文件，再检查分享策略。':'文件实体正在销毁或已经销毁。全部下载历史仍可在记录中查看。') ?></section><?php else: ?>
<form method="post" action="<?= h($fileUrl) ?>/policy" class="policy-form" data-policy-form data-current-count="<?= (int)$file['public_count'] ?>" data-current-cap="<?= $file['public_cap']===null?'':(int)$file['public_cap'] ?>" data-current-auto="<?= (int)$file['auto_destroy'] ?>" data-filename="<?= h($file['name']) ?>">
<?php sf_csrf($manager) ?><input type="hidden" name="policy_version" value="<?= (int)$file['policy_version'] ?>">
<section class="panel form-panel"><div class="form-section-heading"><span class="section-icon"><?= sf_icon('globe') ?></span><div><h2>分享状态</h2><p>仅影响新下载，已获准的下载仍可继续。</p></div></div><div class="radio-cards"><label class="radio-card"><input type="radio" name="state" value="active" <?= $file['state']!=='paused'?'checked':'' ?>><span><strong>开放分享</strong><small>允许符合密码与额度规则的新下载</small></span><?= sf_icon('check-circle') ?></label><label class="radio-card"><input type="radio" name="state" value="paused" <?= $file['state']==='paused'?'checked':'' ?>><span><strong>暂停新下载</strong><small>保留累计和当前剩余名额</small></span><?= sf_icon('pause') ?></label></div></section>
<section class="panel form-panel"><div class="form-section-heading"><span class="section-icon"><?= sf_icon('lock') ?></span><div><h2>分享密码 <span class="small-badge"><?= $file['has_password']?'已设置':'未设置' ?></span></h2><p>密码只用于验证，不会回显或出现在分享链接中。</p></div></div><div class="form-grid"><label>密码操作<select name="password_action" data-password-action><option value="keep">保持当前状态</option><option value="set"><?= $file['has_password']?'更换密码':'设置新密码' ?></option><?php if($file['has_password']): ?><option value="remove">移除密码</option><?php endif ?></select></label><label data-password-field>新密码<input type="password" name="password" minlength="4" maxlength="512" autocomplete="new-password" placeholder="至少 4 个字符" data-new-password><small>只有选择设置或更换密码时才会生效</small></label></div><label class="checkbox-row"><input type="checkbox" name="revoke" value="1"><span><strong>同时撤销现有下载授权</strong><small>让后续请求及续传失效。已交给服务器的在途响应可能仍会完成。</small></span></label></section>
<section class="panel form-panel"><div class="form-section-heading"><span class="section-icon"><?= sf_icon('download') ?></span><div><h2>下载额度</h2><p>累计公开下载 <?= sf_number($file['public_count']) ?> 次 · <?= $file['remaining']===null?'当前不限次':'剩余 '.sf_number($file['remaining']).' 次' ?></p></div></div><div class="form-grid"><label>调整方式<select name="quota_mode" data-quota-mode><option value="keep">保持当前额度</option><?php if($file['public_cap']!==null): ?><option value="add">再增加 N 次（推荐）</option><?php endif ?><option value="remaining">从现在起允许 N 次</option><option value="unlimited">不限次数</option></select></label><label data-quota-field>下载名额 N<input type="number" name="quota_amount" min="1" max="100000000" step="1" inputmode="numeric" placeholder="例如 10" data-quota-amount><small>仅增加或重新设置额度时填写</small></label></div><div class="quota-preview" data-quota-preview aria-live="polite"><?= sf_icon('info') ?><span data-quota-preview-text><?= $file['remaining']===null?'保存后仍不限次数，累计不变。':'保存后剩余 '.sf_number($file['remaining']).' 次，累计不变。' ?></span></div></section>
<section class="panel form-panel destroy-policy"><div class="form-section-heading"><span class="section-icon"><?= sf_icon('shield') ?></span><div><h2>到额后的处理</h2><p>默认只停止新下载。自动销毁需明确确认。</p></div></div><label class="checkbox-row"><input type="checkbox" name="auto_destroy" value="1" <?= $file['auto_destroy']?'checked':'' ?> data-auto-destroy><span><strong>达到下载额度后，自动永久删除服务器文件</strong><small>保护已获准的下载，等待有效会话结束后再删除文件实体。</small></span></label><div class="destruction-confirmation" data-destruction-confirmation><div class="notice warning"><?= sf_icon('alert') ?><span><strong>此动作无法通过本应用恢复</strong><br>目标：<?= h($file['name']) ?><br><span data-destruction-threshold>达到累计 <?= $file['public_cap']===null?'待设置':sf_number($file['public_cap']) ?> 次后触发</span>。已有下载授权失效且无在途传输后，服务器文件实体将被永久删除；全部元数据与记录保留。外部备份不在删除范围内。</span></div><label>输入完整文件名确认<input type="text" name="confirm_destroy" autocomplete="off" spellcheck="false" placeholder="<?= h($file['name']) ?>" data-confirm-destroy><small>启用自动销毁或变更触发额度时，必须重新输入文件名确认</small></label></div></section>
<div class="form-save-bar"><span><?= sf_icon('shield') ?>策略版本 <?= (int)$file['policy_version'] ?> · 保存时检查配置冲突</span><button class="button primary" type="submit" data-busy-label="保存中…"><?= sf_icon('check') ?>保存分享设置</button></div>
</form>
<?php endif ?>
<?php elseif($tab==='downloads'): ?>
<section class="panel"><div class="panel-heading"><div><h2>公开下载记录</h2><p>当前文件 · 近 <?= (int)($data['range']['days']??30) ?> 天</p></div><a class="text-link" href="<?= h(sf_url('/admin/downloads',['file_id'=>$fileId,'days'=>30])) ?>">筛选与导出<?= sf_icon('arrow') ?></a></div><?php sf_events_table($events,$timezone) ?><?php sf_pagination($pagination,$fileUrl) ?></section><div class="definition-note"><?= sf_icon('info') ?><p>历史迁入 <?= sf_number($file['legacy_count']) ?> 次，仅有累计时不会补造逐次记录。后台专用下载保存在管理审计中。</p></div>
<?php endif ?>
<?php if($tab!=='downloads'): ?>
<?php if($file['state']==='trashed'): ?><section class="panel recovery-panel"><div><h2><?= sf_icon('restore') ?>从回收目录恢复</h2><p>恢复后将保持暂停，累计与剩余名额不变。请检查设置后重新开放。</p></div><form method="post" action="<?= h($fileUrl) ?>/restore"><?php sf_csrf($manager) ?><button class="button secondary" type="submit"><?= sf_icon('restore') ?>恢复文件</button></form></section>
<?php elseif(!in_array($file['state'],['destroyed','destroying','missing'],true)): ?><details class="danger-zone"><summary><?= sf_icon('trash') ?>移入回收目录<?= sf_icon('chevron-down') ?></summary><form method="post" action="<?= h($fileUrl) ?>/trash" data-confirm-form data-confirm-filename="<?= h($file['name']) ?>"><?php sf_csrf($manager) ?><p>关闭此文件的分享，并将实体移到回收目录。下载历史继续保留；之后可从这里恢复。</p><label>输入完整文件名确认<input type="text" name="confirmation" placeholder="<?= h($file['name']) ?>" autocomplete="off" required></label><button class="button danger" type="submit"><?= sf_icon('trash') ?>确认移入回收目录</button></form></details><?php endif ?>
<?php endif ?>
</div>
