<?php $filters=$data['filters']??$_GET;$hasFilters=!empty($filters['q'])||!empty($filters['state'])||!empty($filters['password']); ?>
<div class="page-heading"><div><div class="eyebrow">分享，从这里开始</div><h1>文件管理 <span class="heading-count"><?= sf_number($pagination['total']??count($files)) ?></span></h1><p>管理文件、分享权限与下载额度。</p></div><div class="heading-actions"><form method="post" action="/admin/scan" class="inline-form"><?php sf_csrf($manager) ?><button class="button secondary" type="submit" data-busy-label="扫描中…"><?= sf_icon('refresh') ?>扫描目录</button></form><button class="button primary" type="button" data-open-upload><?= sf_icon('upload') ?>上传文件</button></div></div>
<section class="panel file-panel">
<form method="get" action="/admin/files" class="file-toolbar" aria-label="筛选文件">
  <div class="search-input"><?= sf_icon('search') ?><label class="sr-only" for="file-search">搜索文件名</label><input id="file-search" type="search" name="q" placeholder="搜索文件名…" value="<?= h($filters['q']??'') ?>" autocomplete="off"><kbd aria-hidden="true">/</kbd></div>
  <div class="toolbar-filters"><label class="select-label"><span class="sr-only">分享状态</span><select name="state" aria-label="分享状态"><option value="">全部状态</option><?php foreach(['active','paused','exhausted','missing','destroy_pending','destroying','destroyed','trashed','attention']as$s): ?><option value="<?= h($s) ?>" <?= ($filters['state']??'')===$s?'selected':'' ?>><?= h($s==='attention'?'需要处理':sf_status_label($s)) ?></option><?php endforeach ?></select></label><label class="select-label"><span class="sr-only">密码筛选</span><select name="password" aria-label="密码筛选"><option value="">全部密码状态</option><option value="yes" <?= ($filters['password']??'')==='yes'?'selected':'' ?>>已设置密码</option><option value="no" <?= ($filters['password']??'')==='no'?'selected':'' ?>>无密码</option></select></label><label class="select-label"><span class="sr-only">文件排序</span><select name="sort" aria-label="文件排序"><?php foreach(['newest'=>'最新导入','name'=>'文件名','downloads'=>'公开累计最多','size'=>'文件最大']as$value=>$label): ?><option value="<?= h($value) ?>" <?= ($filters['sort']??'newest')===$value?'selected':'' ?>><?= h($label) ?></option><?php endforeach ?></select></label><button class="button secondary filter-submit" type="submit"><?= sf_icon('filter') ?><span>筛选</span></button></div>
</form>
<?php if($hasFilters): ?><div class="active-filters"><span>当前筛选</span><?php if(!empty($filters['q'])): ?><span class="filter-chip">名称：<?= h($filters['q']) ?></span><?php endif ?><?php if(!empty($filters['state'])): ?><span class="filter-chip"><?= h($filters['state']==='attention'?'需要处理':sf_status_label($filters['state'])) ?></span><?php endif ?><?php if(!empty($filters['password'])): ?><span class="filter-chip"><?= $filters['password']==='yes'?'已设置密码':'无密码' ?></span><?php endif ?><a href="/admin/files">清除筛选</a></div><?php endif ?>
<div class="bulk-toolbar" data-bulk-toolbar hidden><span><strong data-selection-count>0</strong> 个文件已选</span><div><button class="button secondary small" type="button" data-copy-selected><?= sf_icon('copy') ?>复制所选链接</button><button class="button ghost small" type="button" data-clear-selection>取消选择</button></div></div>
<?php if(!$files): ?>
<?php sf_empty($hasFilters?'search':'folder',$hasFilters?'没有匹配的文件':'把第一个文件放进来',$hasFilters?'试试其他关键词，或清除筛选后重新查看。':'上传一个文件，或扫描现有目录。导入完成后即可复制分享链接。',$hasFilters?'/admin/files':null,$hasFilters?'清除筛选':null) ?>
<?php if(!$hasFilters): ?><div class="empty-actions"><button class="button primary" type="button" data-open-upload><?= sf_icon('upload') ?>上传第一个文件</button></div><?php endif ?>
<?php else: ?>
<div class="table-wrap"><table class="data-table files-table"><thead><tr><th class="selection-cell"><label class="checkbox-label"><input type="checkbox" data-select-all aria-label="选择当前页所有文件"></label></th><th>文件名</th><th>分享状态</th><th>密码</th><th class="align-right">公开累计</th><th class="align-right">剩余名额</th><th>最近公开下载</th><th class="align-right">操作</th></tr></thead><tbody>
<?php foreach($files as$item): [$typeIcon,$typeColor,$typeLabel]=sf_file_type($item);$url=public_download_url($item); ?>
<tr data-file-row><td class="selection-cell"><label class="checkbox-label"><input type="checkbox" data-select-file value="<?= (int)$item['id'] ?>" data-public-url="<?= h($url) ?>" aria-label="选择 <?= h($item['name']) ?>"></label></td><td class="file-primary" data-label="文件"><div class="table-file"><?= sf_file_icon($item) ?><div><a class="file-name" data-file-drawer href="/admin/files/<?= (int)$item['id'] ?>" title="<?= h($item['name']) ?>"><?= h($item['name']) ?></a><span class="cell-subtle"><?= h($typeLabel) ?><i class="separator">·</i><?= h(format_bytes($item['bytes'])) ?></span><form method="post" action="/admin/files/<?= (int)$item['id'] ?>/visibility" class="visibility-form"><?php sf_csrf($manager) ?><input type="hidden" name="visible" value="<?= $item['homepage_visible']?'0':'1' ?>"><button type="submit" role="switch" aria-checked="<?= $item['homepage_visible']?'true':'false' ?>" aria-label="在首页显示 <?= h($item['name']) ?>" class="visibility-switch"><span class="switch-track" aria-hidden="true"></span><span>首页显示</span><strong><?= $item['homepage_visible']?'开':'关' ?></strong></button></form><?php if($item['upload_origin']==='guest'): ?><span class="cell-subtle">访客上传</span><?php endif ?></div></div></td><td class="file-state" data-label="分享状态"><?= sf_badge($item['state']) ?></td><td data-label="密码"><span class="password-state<?= $item['has_password']?' secured':'' ?>"><?= sf_icon($item['has_password']?'lock':'unlock') ?><?= $item['has_password']?'已设置':'无密码' ?></span></td><td class="align-right count-cell" data-label="公开累计"><strong><?= sf_number($item['public_count']) ?></strong><span class="mobile-unit"> 次</span></td><td class="align-right count-cell" data-label="剩余名额"><strong class="<?= $item['remaining']===0?'warning-text':'' ?>"><?= $item['remaining']===null?'<span class="infinity" aria-label="不限次">∞</span>':sf_number($item['remaining']) ?></strong><span class="mobile-unit"><?= $item['remaining']===null?' 不限次':' 次' ?></span></td><td data-label="最近公开下载"><span class="time-value<?= empty($item['last_public_at'])?' muted':'' ?>"><?= h(sf_date($item['last_public_at'],$timezone)) ?></span></td><td class="file-actions align-right"><div class="row-actions"><button class="button secondary small copy-button" type="button" data-copy="<?= h($url) ?>" data-copy-label="分享链接"><?= sf_icon('copy') ?><span>复制链接</span></button><a class="icon-button" data-file-drawer href="/admin/files/<?= (int)$item['id'] ?>" aria-label="管理 <?= h($item['name']) ?>" title="文件详情"><?= sf_icon('chevron') ?></a></div></td></tr>
<?php endforeach ?>
</tbody></table></div>
<?php endif ?>
<?php sf_pagination($pagination,'/admin/files') ?>
</section>
<div class="definition-note"><?= sf_icon('info') ?><p>累计与剩余名额不会因暂停、重新开放或增加名额而重置。后台下载请使用文件详情中的专用按钮。</p></div>
