<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><meta name="referrer" content="no-referrer"><title><?= h($title) ?> · Share Files</title><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/app.css?v=20261002"><script src="/assets/app.js?v=20261002" defer></script></head><body class="public-page">
<header class="public-header"><a class="brand" href="<?= $page==='login'?'/admin/login':'/' ?>"><span class="brand-symbol"><?= sf_icon('folder') ?></span><span>Share Files</span></a><?php if($page!=='login'): ?><span class="public-security"><?= sf_icon('shield') ?>安全文件分享</span><?php endif ?></header>
<main class="public-main"><section class="auth-card" aria-labelledby="auth-title">
<?php if($page==='login'): ?>
<span class="auth-icon"><?= sf_icon('lock') ?></span><span class="eyebrow">你的分享工作空间</span><h1 id="auth-title">欢迎回来</h1><p class="auth-description">登录以管理文件与查看下载记录</p>
<?php if($error): ?><div class="notice error" role="alert"><?= sf_icon('alert') ?><span><?= h($error) ?></span></div><?php endif ?>
<form method="post" action="/admin/login" class="auth-form"><?php sf_csrf($manager) ?><label>管理账号<input name="username" type="text" autocomplete="username" required autofocus value="<?= h(is_string($_POST['username']??null)?$_POST['username']:'') ?>" placeholder="输入管理账号"></label><label>密码<div class="password-input"><input name="password" type="password" autocomplete="current-password" required placeholder="输入管理密码" id="login-password"><button type="button" class="icon-button" data-toggle-password="login-password" aria-label="显示密码" aria-pressed="false"><?= sf_icon('eye') ?></button></div></label><button class="button primary full-width" type="submit" data-busy-label="正在登录…">登录工作空间<?= sf_icon('arrow') ?></button></form><p class="auth-footnote"><?= sf_icon('shield') ?>管理界面与公开下载相互独立</p>
<?php elseif($page==='password'): ?>
<?= sf_file_icon($file??['name'=>'文件'],'auth-file-icon') ?><span class="eyebrow">受密码保护的分享</span><h1 id="auth-title">输入分享密码</h1><p class="auth-description">验证后将自动开始下载</p><div class="shared-file-preview"><strong><?= h($file['name']??'文件') ?></strong><span><?= h(format_bytes((int)($file['bytes']??0))) ?></span></div>
<?php if($error): ?><div class="notice error" role="alert"><?= sf_icon('alert') ?><span><?= h($error) ?></span></div><?php endif ?>
<form method="post" action="<?= h($data['unlock_url']??'') ?>" class="auth-form"><input type="hidden" name="csrf" value="<?= h($data['csrf']??$manager['csrf']??'') ?>"><input type="hidden" name="flow" value="<?= h($data['flow']??'') ?>"><label>分享密码<div class="password-input"><input type="password" name="password" id="share-password" required autofocus autocomplete="off" placeholder="向分享者获取密码"><button type="button" class="icon-button" data-toggle-password="share-password" aria-label="显示密码" aria-pressed="false"><?= sf_icon('eye') ?></button></div></label><button class="button primary full-width" type="submit" data-busy-label="正在验证…"><?= sf_icon('download') ?>验证并下载</button></form><p class="auth-footnote"><?= sf_icon('lock') ?>密码仅用于本次验证，不会出现在链接中</p>
<?php else: ?>
<span class="auth-icon error-icon"><?= sf_icon(in_array($errorCode,['paused','exhausted','destroy_pending','expired'],true)?'clock':'alert') ?></span><span class="eyebrow">SHARE FILES · <?= (int)($data['http_status']??400) ?></span><h1 id="auth-title"><?= h(match($errorCode){'conflict'=>'设置已在其他窗口变更','paused'=>'分享已暂停','exhausted'=>'下载名额已用完','destroy_pending'=>'等待已有下载结束','destroying'=>'文件正在销毁','destroyed'=>'文件已永久销毁','expired'=>'下载授权已过期','missing'=>'文件暂时不可用','not_found'=>'未找到这个页面','rate_limit'=>'请稍后重试',default=>'暂时无法完成'}) ?></h1><p class="auth-description error-description"><?= h($error?:'请稍后重试，或联系分享者。') ?></p><div class="error-actions"><?php if(!empty($manager['admin'])): ?><a class="button primary full-width" href="/admin/files">返回文件管理<?= sf_icon('arrow') ?></a><button class="button secondary full-width" type="button" data-go-back>返回上一页</button><?php else: ?><button class="button primary full-width" type="button" data-go-back>返回上一页</button><p class="form-hint">如问题持续，请联系提供分享链接的人</p><?php endif ?></div><?php if($errorCode==='conflict'): ?><p class="auth-footnote">请重新打开文件设置，比对最新配置后再保存</p><?php endif ?>
<?php endif ?>
</section><div class="public-footer">Share Files<span>简单分享，安心交付</span></div></main>
<div id="toast" class="toast" role="status" aria-live="polite" hidden></div>
</body></html>
