<?php $window=$data['window'];$active=$window['active'];$uploadUrl=$active?canonical_base().'/upload/'.$window['token']:''; ?>
<div class="page-heading"><div><div class="eyebrow">给文件留一个入口</div><h1>访客收件</h1><p>按需开启收件窗口，让人或 Agent 把文件交给你。</p></div></div>
<section class="panel receive-control" data-receive-window data-expires="<?= $active?(int)$window['expires_at']:0 ?>" data-server-time="<?= time() ?>">
  <div class="receive-state"><span class="receive-dot <?= $active?'is-open':'' ?>"></span><div><h2 data-window-label><?= $active?'正在接收文件':'收件入口已关闭' ?></h2><p data-window-countdown><?= $active?'截止 '.h(sf_date($window['expires_at'],$timezone)):'开启后才能上传；到期自动关闭。' ?></p></div><?php if($active): ?><form method="post" action="/admin/receive/close"><?php sf_csrf($manager) ?><button class="button secondary" type="submit">立即关闭</button></form><?php endif ?></div>
  <form method="post" action="/admin/receive/open" class="receive-open-form"><?php sf_csrf($manager) ?><label for="receive-minutes">启用时长<span class="duration-input"><input id="receive-minutes" name="minutes" type="number" min="1" max="1440" value="10" required inputmode="numeric"><span>分钟</span></span></label><button class="button primary" type="submit"><?= sf_icon('upload') ?><?= $active?'重新开启并换链接':'开启访客上传' ?></button></form>
  <p class="form-hint">1–1440 分钟。每次开启会生成新链接，旧链接立即失效。关闭收件不会删除已收到的文件。</p>
  <?php if($active): ?><div class="receive-link" data-active-receive-link><label for="receive-link">本次收件链接</label><div><input id="receive-link" readonly value="<?= h($uploadUrl) ?>"><button type="button" class="button secondary" data-copy="<?= h($uploadUrl) ?>" data-copy-label="收件链接"><?= sf_icon('copy') ?>复制链接</button><a class="button ghost" href="<?= h($uploadUrl) ?>" target="_blank" rel="noopener noreferrer">预览</a></div><p>本窗口已收到 <?= sf_number($window['received_count']) ?> 个文件 · <?= h(format_bytes((int)$window['received_bytes'])) ?>。只把链接发给需要上传的人。</p></div><?php endif ?>
  <div class="quiet-note">单文件最多 45 MiB。本次窗口最多 100 个文件、合计 1 GiB；收到的文件默认不公开。浏览器与 Agent 使用同一条收件链接。</div>
</section>
<section class="panel"><div class="panel-heading"><div><h2>收到的文件</h2><p>访客无法浏览这里。你可以直接下载，或进入文件详情管理。</p></div><a class="text-link" href="/admin/receive">刷新<?= sf_icon('refresh') ?></a></div>
<?php if(!$files): sf_empty('upload','还没有收到文件','开启上方收件窗口并发送链接，上传成功后文件会出现在这里。'); else: ?>
<div class="table-wrap"><table class="data-table inbox-table"><thead><tr><th>文件</th><th>收到时间</th><th>状态</th><th class="align-right">操作</th></tr></thead><tbody>
<?php foreach($files as$item): ?><tr><td data-label="文件"><div class="table-file"><?= sf_file_icon($item) ?><div><a class="file-name" href="/admin/files/<?= (int)$item['id'] ?>" title="<?= h($item['name']) ?>"><?= h($item['name']) ?></a><span class="cell-subtle"><?= h(format_bytes($item['bytes'])) ?> · <?= $item['homepage_visible']?'已允许首页展示':'首页隐藏' ?></span></div></div></td><td data-label="收到时间"><?= h(sf_date($item['created_at'],$timezone)) ?></td><td data-label="状态"><?= sf_badge($item['state']) ?></td><td data-label="操作"><div class="row-actions"><?php if(!in_array($item['state'],['trashed','destroyed','destroying','missing'],true)): ?><form method="post" action="/admin/files/<?= (int)$item['id'] ?>/download-ticket" data-download-form><?php sf_csrf($manager) ?><button class="button secondary small" type="submit"><?= sf_icon('download') ?>后台下载</button></form><?php endif ?><a class="button ghost small" href="/admin/files/<?= (int)$item['id'] ?>">管理</a></div></td></tr><?php endforeach ?>
</tbody></table></div><?php sf_pagination($pagination,'/admin/receive'); endif ?></section>
<script src="/assets/guest-upload.js?v=20261002-guest" defer></script>
