<?php
$now=new DateTimeImmutable('now',new DateTimeZone($timezone));$auditLabels=['scan'=>'扫描目录','settings'=>'更新工作空间设置','policy'=>'更改分享策略','download_ticket'=>'创建后台下载','trash'=>'移入回收目录','restore'=>'恢复文件','auto_destroy'=>'到额自动销毁','export'=>'导出下载记录','login'=>'管理员登录','logout'=>'管理员退出','upload'=>'上传文件'];
?>
<div class="page-heading"><div><div class="eyebrow">为你的工作方式而设</div><h1>设置</h1><p>显示偏好、下载默认规则，以及工作空间状态。</p></div></div>
<div class="settings-layout"><nav class="settings-navigation" aria-label="设置栏目"><a href="#display-settings" class="active"><?= sf_icon('globe') ?>显示与时区</a><a href="#download-settings"><?= sf_icon('download') ?>下载策略</a><a href="#log-settings"><?= sf_icon('history') ?>记录与地区</a><a href="#storage-settings"><?= sf_icon('server') ?>存储状态</a><a href="#account-settings"><?= sf_icon('user') ?>管理账户</a></nav><div class="settings-sections">
<form method="post" action="/admin/settings" data-settings-form>
<?php sf_csrf($manager) ?>
<section class="panel form-panel" id="display-settings"><div class="form-section-heading"><span class="section-icon"><?= sf_icon('globe') ?></span><div><h2>显示与时区</h2><p>只改变显示和统计分桶，不改写历史时间。</p></div></div><label class="wide-field">显示时区<select name="timezone" data-timezone-select><?php foreach(DateTimeZone::listIdentifiers()as$tz): ?><option value="<?= h($tz) ?>" <?= $timezone===$tz?'selected':'' ?>><?= h($tz) ?></option><?php endforeach ?></select></label><div class="timezone-preview"><span><?= sf_icon('clock') ?>当前时间预览</span><strong class="mono" data-timezone-preview><?= h($now->format('Y年n月j日 H:i:s')) ?></strong><small data-timezone-offset><?= h($now->format('P')) ?> · <?= h($timezone) ?></small></div><p class="form-hint">所有日期范围均按此时区解释。夏令时地区的单个自然日可能是 23 或 25 小时。</p></section>
<section class="panel form-panel" id="download-settings"><div class="form-section-heading"><span class="section-icon"><?= sf_icon('download') ?></span><div><h2>下载策略</h2><p>公开下载与后台下载相互独立。</p></div></div><label class="wide-field">已获准下载的续传有效期<select name="session_ttl"><?php $ttl=(int)($settings['session_ttl']??86400);$ttls=[3600=>'1 小时',21600=>'6 小时',43200=>'12 小时',86400=>'24 小时（建议）',172800=>'48 小时'];if(!isset($ttls[$ttl]))$ttls[$ttl]=$ttl.' 秒（当前值）';foreach($ttls as$sec=>$label): ?><option value="<?= $sec ?>" <?= $ttl===$sec?'selected':'' ?>><?= h($label) ?></option><?php endforeach ?></select><small>对之后获准的新会话生效。有效期内同一会话续传不重复扣除名额。</small></label><dl class="policy-defaults"><div><dt>首次认领窗口</dt><dd>5 分钟</dd></div><div><dt>新文件公开额度</dt><dd>不限次</dd></div><div><dt>新文件分享密码</dt><dd>默认关闭</dd></div><div><dt>到额自动永久销毁</dt><dd><span class="badge badge-paused">默认关闭</span></dd></div></dl><p class="form-hint">需要自动销毁时，在文件的分享设置中单独启用并确认。中断不会自动退还名额。</p></section>
<div class="form-save-bar settings-save"><span>修改保存后生效</span><button class="button primary" type="submit" data-busy-label="保存中…"><?= sf_icon('check') ?>保存设置</button></div>
</form>
<section class="panel form-panel" id="log-settings"><div class="form-section-heading"><span class="section-icon"><?= sf_icon('history') ?></span><div><h2>记录与地区</h2><p>清楚记录已知信息，不推断未知细节。</p></div></div><dl class="property-list compact"><div><dt>明细启用时间</dt><dd><?= h(sf_date($storage['detail_started_at']??$settings['detail_started_at']??null,$timezone)) ?></dd></div><div><dt>本机地区库</dt><dd><?= h($storage['geo_status']??'配置状态未知') ?></dd></div><div><dt>地区数据来源</dt><dd><?= h($storage['geo_version']??'未配置') ?></dd></div><div><dt>来源记录</dt><dd>清除凭据、查询参数与片段</dd></div><div><dt>日志保留</dt><dd>保留全部历史，不自动清理</dd></div></dl><div class="quiet-note"><?= sf_icon('shield') ?><p>地区在本机查询，不逐次向外部 API 发送访客 IP。文件移除后下载记录仍然保留。</p></div><details class="geo-setup"><summary>地区库安装与更新<?= sf_icon('chevron-down') ?></summary><p>服务器管理员可安装 DB-IP City Lite。本机读取地区数据，浏览器不会下载或执行安装操作。请先阅读并确认接受 <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">CC BY 4.0 许可</a>。</p><div class="setup-command"><code>php scripts/geoip.php install --accept-dbip-license</code><button class="icon-button" type="button" data-copy="php scripts/geoip.php install --accept-dbip-license" data-copy-label="安装命令" aria-label="复制地区库安装命令"><?= sf_icon('copy') ?></button></div><p>数据来源：<a href="https://db-ip.com" target="_blank" rel="noopener noreferrer">IP Geolocation by DB-IP</a>。近似地区可能与访客真实位置不同。</p></details></section>
<section class="panel form-panel" id="storage-settings"><div class="form-section-heading"><span class="section-icon"><?= sf_icon('server') ?></span><div><h2>存储状态</h2><p>运行状态概览，不展示服务器路径与运维凭据。</p></div></div><div class="storage-grid"><div><span>受管理文件</span><strong><?= sf_number($storage['files']??0) ?><small> 个</small></strong></div><div><span>文件实体大小</span><strong><?= h(format_bytes((int)($storage['bytes']??0))) ?></strong></div><div><span>元数据数据库</span><strong><?= h(format_bytes((int)($storage['database_bytes']??0))) ?></strong></div><div><span>所在磁盘可用空间</span><strong><?= isset($storage['free_bytes'])?h(format_bytes((int)$storage['free_bytes'])):'暂不可读' ?></strong></div></div><?php if(!empty($data['jobs'])): ?><div class="pending-jobs"><h3><?= sf_icon('clock') ?>等待处理的到额任务</h3><?php foreach($data['jobs']as$job): ?><a href="/admin/files/<?= (int)$job['file_id'] ?>"><span><?= h($job['name']) ?><small><?= !empty($job['error'])?'处理暂缓，请检查实体与传输状态':'保护有效下载会话，等待安全处理' ?></small></span><span class="badge badge-destroy_pending"><?= $job['status']==='running'?'处理中':'等待中' ?></span></a><?php endforeach ?></div><?php else: ?><p class="status-line"><?= sf_icon('check-circle') ?>暂无等待处理的自动销毁任务</p><?php endif ?><form method="post" action="/admin/scan"><?php sf_csrf($manager) ?><button class="button secondary" type="submit" data-busy-label="扫描中…"><?= sf_icon('refresh') ?>扫描目录 / 重新索引</button></form><p class="form-hint">保持现有目录投递方式。扫描只在首次导入或内容变更时计算 SHA256。</p></section>
<section class="panel form-panel" id="account-settings"><div class="form-section-heading"><span class="section-icon"><?= sf_icon('user') ?></span><div><h2>管理账户</h2><p>只有已认证的管理员可访问完整下载记录。</p></div></div><div class="account-setting-row"><span class="account-avatar large"><?= sf_icon('user') ?></span><div><strong><?= h($manager['username']??'管理员') ?></strong><small>当前登录账户 · 安全会话</small></div><form method="post" action="/admin/logout"><?php sf_csrf($manager) ?><button class="button secondary" type="submit">退出登录</button></form></div><p class="form-hint">管理口令通过服务器上的安全配置维护，不在普通页面展示。退出登录会使当前管理下载授权失效。</p></section>
<section class="panel"><div class="panel-heading"><div><h2>近期管理活动</h2><p>管理下载、设置调整与文件操作独立审计</p></div><span class="small-badge">最近 12 条</span></div><?php if(empty($data['audit'])): sf_empty('history','暂无管理活动','上传、扫描和分享策略变更会记录在这里。'); else: ?><ul class="audit-list"><?php foreach($data['audit']as$audit): ?><li><span class="audit-icon"><?= sf_icon($audit['action']==='download_ticket'?'download':($audit['action']==='auto_destroy'?'trash':'history')) ?></span><div><strong><?= h($auditLabels[$audit['action']]??$audit['action']) ?></strong><span><?= h($audit['actor']) ?><?php if($audit['file_id']): ?> · <a href="/admin/files/<?= (int)$audit['file_id'] ?>">文件 #<?= (int)$audit['file_id'] ?></a><?php endif ?></span></div><time><?= h(sf_date($audit['occurred_at'],$timezone)) ?></time></li><?php endforeach ?></ul><?php endif ?></section>
</div></div>
